### ISSUE TITLE
Support for different architectures

### ISSUE THREAD

**Issue by yaghmr** [elfmaster/libelfmaster#40]
I'm wondering how much work it'll take to support various architectures like ARM and AArch64 on top of what we already have. 
Any ideas or suggestions on this? 
Any thoughts or advice on this would be awesome

**Comment by elfmaster** [comment]
There is aarch64 branch that isn't yet complete but has enough functionality for most elf parsing tasks. I'll be finishing it and merging it into the main branch very soon.
